%YAML 1.2
---
daqiri:
  cfg:
    version: 1
    stream_type: "raw"
    master_core: 8
    debug: false
    log_level: "info"
    loopback: ""

    memory_regions:
    - name: "Data_RX_HOST_PINNED"
      kind: "host_pinned"
      affinity: 0
      num_bufs: 4096
      buf_size: 2048

    interfaces:
    - name: "rx_port"
      address: 0000:01:00.0
      rx:
        flow_isolation: true
        queues:
        - name: "rx_q_0"
          id: 0
          cpu_core: 18
          batch_size: 64
          memory_regions:
            - "Data_RX_HOST_PINNED"
        flows:
        - name: "flow_0"
          id: 0
          action:
            type: queue
            id: 0
          match:
            udp_dst: 42337

bench_rx:
  interface_name: "rx_port"
