#!/usr/bin/env bash
set -euo pipefail

IMAGE_TAG="${IMAGE_TAG:-daqiri:local}"
BASE_TARGET="${BASE_TARGET:-dpdk}"
BASE_IMAGE="${BASE_IMAGE:-cuda}"
DAQIRI_ENGINE="${DAQIRI_ENGINE:-dpdk ibverbs}"
DAQIRI_BUILD_PYTHON="${DAQIRI_BUILD_PYTHON:-OFF}"
DAQIRI_BUILD_EXAMPLES="${DAQIRI_BUILD_EXAMPLES:-ON}"
DAQIRI_BUILD_APPLICATIONS="${DAQIRI_BUILD_APPLICATIONS:-OFF}"
DAQIRI_BUILD_RESNET50_INFERENCE="${DAQIRI_BUILD_RESNET50_INFERENCE:-ON}"
DAQIRI_BUILD_UCX_GPU_EGRESS="${DAQIRI_BUILD_UCX_GPU_EGRESS:-OFF}"
DAQIRI_ENABLE_S3="${DAQIRI_ENABLE_S3:-OFF}"
BUILD_SHARED_LIBS="${BUILD_SHARED_LIBS:-ON}"
DAQIRI_ENABLE_OTEL_METRICS="${DAQIRI_ENABLE_OTEL_METRICS:-OFF}"
AWS_SDK_CPP_VERSION="${AWS_SDK_CPP_VERSION:-1.11.822}"
UCX_VERSION="${UCX_VERSION:-1.20.0}"
UCX_SHA256="${UCX_SHA256:-7c8a6093cada179aa1d851b83625e3b25ed5658966e309de5118c27a038c7ef9}"

case "${BASE_IMAGE}" in
  cuda)
    DAQIRI_OS_BASE_IMAGE="nvcr.io/nvidia/cuda:13.1.0-devel-ubuntu24.04"
    ;;
  torch)
    DAQIRI_OS_BASE_IMAGE="nvcr.io/nvidia/pytorch:26.01-py3"
    ;;
  *)
    echo "ERROR: invalid BASE_IMAGE='${BASE_IMAGE}'. Choose from: cuda, torch" >&2
    exit 1
    ;;
esac

docker build \
  --target runtime \
  --build-arg DAQIRI_BASE_TARGET="${BASE_TARGET}" \
  --build-arg DAQIRI_OS_BASE_IMAGE="${DAQIRI_OS_BASE_IMAGE}" \
  --build-arg DAQIRI_ENGINE="${DAQIRI_ENGINE}" \
  --build-arg DAQIRI_BUILD_PYTHON="${DAQIRI_BUILD_PYTHON}" \
  --build-arg DAQIRI_BUILD_EXAMPLES="${DAQIRI_BUILD_EXAMPLES}" \
  --build-arg DAQIRI_BUILD_APPLICATIONS="${DAQIRI_BUILD_APPLICATIONS}" \
  --build-arg DAQIRI_BUILD_RESNET50_INFERENCE="${DAQIRI_BUILD_RESNET50_INFERENCE}" \
  --build-arg DAQIRI_BUILD_UCX_GPU_EGRESS="${DAQIRI_BUILD_UCX_GPU_EGRESS}" \
  --build-arg DAQIRI_ENABLE_S3="${DAQIRI_ENABLE_S3}" \
  --build-arg BUILD_SHARED_LIBS="${BUILD_SHARED_LIBS}" \
  --build-arg DAQIRI_ENABLE_OTEL_METRICS="${DAQIRI_ENABLE_OTEL_METRICS}" \
  --build-arg AWS_SDK_CPP_VERSION="${AWS_SDK_CPP_VERSION}" \
  --build-arg UCX_VERSION="${UCX_VERSION}" \
  --build-arg UCX_SHA256="${UCX_SHA256}" \
  -t "${IMAGE_TAG}" \
  .

echo "Built ${IMAGE_TAG}"
