/* SPDX-License-Identifier: Apache-2.0 */
#pragma once

/* BAR0 is a DOCA DevEmu stateful region. All registers are little-endian. */
#define DAQIRI_BF3_BAR0_SIZE 0x4000U
#define DAQIRI_BF3_STATEFUL_SIZE 0x100U

#define DAQIRI_BF3_REG_COMMAND 0x00U
#define DAQIRI_BF3_REG_STATUS 0x04U
#define DAQIRI_BF3_REG_ABI_MAGIC 0x08U
#define DAQIRI_BF3_REG_ABI_VERSION 0x0cU
#define DAQIRI_BF3_REG_EPOCH_LO 0x10U
#define DAQIRI_BF3_REG_EPOCH_HI 0x14U

#define DAQIRI_BF3_REG_RING_DMA_LO(id) (0x20U + (id) * 8U)
#define DAQIRI_BF3_REG_RING_DMA_HI(id) (0x24U + (id) * 8U)
#define DAQIRI_BF3_REG_RING_BYTES 0x40U

#define DAQIRI_BF3_REG_REGION_BASE(id) (0x50U + (id) * 0x20U)
#define DAQIRI_BF3_REG_REGION_DMA_LO(id) (DAQIRI_BF3_REG_REGION_BASE(id) + 0x00U)
#define DAQIRI_BF3_REG_REGION_DMA_HI(id) (DAQIRI_BF3_REG_REGION_BASE(id) + 0x04U)
#define DAQIRI_BF3_REG_REGION_BYTES_LO(id) (DAQIRI_BF3_REG_REGION_BASE(id) + 0x08U)
#define DAQIRI_BF3_REG_REGION_BYTES_HI(id) (DAQIRI_BF3_REG_REGION_BASE(id) + 0x0cU)
#define DAQIRI_BF3_REG_REGION_STRIDE(id) (DAQIRI_BF3_REG_REGION_BASE(id) + 0x10U)
#define DAQIRI_BF3_REG_REGION_COUNT(id) (DAQIRI_BF3_REG_REGION_BASE(id) + 0x14U)
#define DAQIRI_BF3_REG_REGION_ID(id) (DAQIRI_BF3_REG_REGION_BASE(id) + 0x18U)
#define DAQIRI_BF3_REG_REGION_DIRECTION(id) (DAQIRI_BF3_REG_REGION_BASE(id) + 0x1cU)

#define DAQIRI_BF3_REG_FATAL_CODE 0x90U
#define DAQIRI_BF3_REG_RESET_COUNT_LO 0x98U
#define DAQIRI_BF3_REG_RESET_COUNT_HI 0x9cU
#define DAQIRI_BF3_REG_RX_COMPLETIONS_LO 0xa0U
#define DAQIRI_BF3_REG_RX_COMPLETIONS_HI 0xa4U
#define DAQIRI_BF3_REG_TX_COMPLETIONS_LO 0xa8U
#define DAQIRI_BF3_REG_TX_COMPLETIONS_HI 0xacU

#define DAQIRI_BF3_CMD_IDLE 0U
#define DAQIRI_BF3_CMD_CONFIGURE 1U
#define DAQIRI_BF3_CMD_START 2U
#define DAQIRI_BF3_CMD_STOP 3U
#define DAQIRI_BF3_CMD_RESET 4U

#define DAQIRI_BF3_REGION_RX 0U
#define DAQIRI_BF3_REGION_TX 1U
#define DAQIRI_BF3_REGION_COUNT 2U

#define DAQIRI_BF3_DEVICE_ID 0xda71U
#define DAQIRI_BF3_VENDOR_ID 0x15b3U
#define DAQIRI_BF3_SUBSYSTEM_ID 0xda71U
#define DAQIRI_BF3_CLASS_CODE 0x058000U
