name: Deploy Documentation

on:
  push:
    branches:
      - website
      - tutorial

permissions:
  contents: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install mkdocs-material

      - name: Build docs
        run: mkdocs build

      - name: Inject custom homepage
        run: |
          cp docs/index.html site/index.html
          cp docs/daqiri-api.html site/daqiri-api.html

      - name: Deploy to GitHub Pages
        run: ghp-import -n -p -f site
